### PR TITLE
Update to HDHR DigitalChannel to use actual protocol data

### PR DESCRIPTION
**Pull request by TPeterson94070**
This should not change anything outside of ChannelDigital.java

### CODE REVIEW

**Comment by sengsational** [comment]
I like what you did with that constructor.  Looks good to me, and I trust that the channels will have better data, now that we're actually not putting hard-coded stuff in them.  There might be nulls, though, if we ask for something out of the XML and the field doesn't exist.  But if we "know" that the data is good, we don't need to test for null every time.

A point of organization: 

I already merged the entire contents of this feature branch into the master, and hoping not to use it again.

My intent was for us to test new features in https://github.com/sengsational/cwhelper/tree/feature_s .  I thought it would make managing the lineup changes more tidy.

This would mean you'd check-out feature_s and be working on that branch.  It was a pita for me to switch to the feature_s branch, but with the help of an [SO answer](https://stackoverflow.com/a/68555273), I did it.

**Comment by TPeterson94070** [comment]
Ah, sorry, I missed the new branch and thought we were just continuing on feature_r.  I'll check out feature_s and see about merging the latest update there instead.

**Comment by TPeterson94070** [comment]
Interestink!  I inadvertently pushed my updated copy of your feature_s branch (after fumbling to get it fetched to my Eclipse repository) to your branch directly.  That didn’t work before when I tried (IIRC) to push to feature_r, so I was surprised that it worked this time.  

Should I continue doing this or, as before, commit to my own forked GitHub repository and submit PR to merge with yours?

**Comment by sengsational** [comment]
I guess I made you all-powerful on my version of the repository, which is fine by me.  It's not going to be like that in other, bigger project collaborations, I don't suppose.  I understand the basics of source control,  but the GitHub specifics quite often baffle me.  I think the best way to do it is the easiest way that still allows us to keep the stuff under development to be isolated.  So as long as we get our feature branch tested and we're happy with it before merging it with master, we're ok.  If it's just as easy for you to work against your copy of the feature branch, that's probably the "expected" way to do it.

**Comment by TPeterson94070** [comment]
I'm going to close this now unnecessary PR.

**Pull request closed without merging**
