### PR TITLE
Added commented code to use with GitHub-hosted CW_EPG_Remote

### PR DESCRIPTION
**Pull request by TPeterson94070**
These two sections of comment show what I think would enable my new CW_EPG_Remote scheme where the stuff that we were adding to CWHelper is instead hosted on https://github.com.  

Access to CWHelper would still be limited to the LAN (assuming that the Windows firewall is configured that way) and we can run the GitHub-hosted stuff as a PWA on any machine on the LAN.

### CODE REVIEW

**Comment by TPeterson94070** [comment]
This version is modified to allow builds on TPeterson94070 or sengsational by changing the "USER" definition only.

**Comment by TPeterson94070** [comment]
In case "closing" this meant that it could not be merged...I'm re-opening it.

**Comment by sengsational** [comment]
I didn't test this, but I presume you're not breaking the cardinal rule "never check-in broken code" :)

**Comment by TPeterson94070** [comment]
It did work here before I checked it in….

 

However, faced with the seemingly intractable HTTPS-on-LAN problem, I’ve been toying with yet another idea:  Stash the EPG, History, and Capture data in the user’s cloud storage (Dropbox, Google Drive, OneDrive, Mega, ???)  That could be done easily from CW_EPG and would solve the HTTPS problem but then it raises the challenge of having CW_EPG_Remote log into the user’s storage service, which I believe to be possible and likely easier to maintain than LAN-based HTTPS, but is also unexplored territory for me.

**Pull request merged**
